// Package codegen is twill's CPU reference backend. It turns a fused ir.Plan
// into C99 source, compiles that source with a C compiler found on the machine,
// loads the result as a shared library, and calls it.
//
// Why C, and why a real compiler.
//
// docs/CODEGEN.md's order of work puts a CPU backend before the GPU one, on the
// grounds that the same IR and the same fusion pass emitting CPU kernels needs
// no dependency and captures the allocation win without the 80-microsecond
// device boundary. That argument is about performance. There is a second and
// more important argument, which is about testability: a backend that *emits*
// rather than interprets is the only kind whose correctness can be tested
// without the device. A closure tree evaluated in Go would be a second
// interpreter wearing a compiler's name, and agreement between two interpreters
// says nothing about whether emitted code is right.
//
// So this backend really does emit. The generated source is C99 that a person
// can read, `gcc -O2` compiles it, and the running program dials into the
// result. Every structural decision it makes -- one function per fused region,
// buffers as offsets into a single arena, index arithmetic materialised as
// constants -- is the decision a CUDA emitter would make, so the later stage
// replaces the emitter and keeps the plumbing.
//
// What it does not do, stated here so no doc has to imply otherwise: it is f64
// only, it is single-threaded, it emits no vector intrinsics and leaves
// vectorisation to the C compiler, and it covers the operator subset in
// internal/ir and nothing else. Anything outside that runs on the interpreter.
package codegen

import (
	"fmt"
	"strings"

	"github.com/martin-k-m/twill/internal/ir"
)

// Layout assigns every materialised value a slice of one flat f64 arena.
//
// One arena rather than one allocation per buffer is what lets the emitted code
// address everything as a compile-time constant offset, and it is also the
// clearest statement of the thing the fusion pass bought: the arena is exactly
// as large as the values that survived fusion.
type Layout struct {
	Offset []int // per node, the element offset into the arena; -1 if not materialised
	Total  int   // arena size in f64 elements
}

func layoutFor(p *ir.Plan) Layout {
	l := Layout{Offset: make([]int, len(p.Graph.Nodes))}
	for i := range l.Offset {
		l.Offset[i] = -1
	}
	for i, n := range p.Graph.Nodes {
		if !p.Materialised[i] {
			continue
		}
		l.Offset[i] = l.Total
		l.Total += ir.Numel(n.Shape)
	}
	if l.Total == 0 {
		l.Total = 1 // a zero-length arena has no address to pass
	}
	return l
}

type emitter struct {
	p   *ir.Plan
	lay Layout
	b   strings.Builder
	err error
}

func (e *emitter) fail(format string, args ...any) {
	if e.err == nil {
		e.err = fmt.Errorf(format, args...)
	}
}

func (e *emitter) printf(format string, args ...any) {
	fmt.Fprintf(&e.b, format, args...)
}

// Emit renders the plan as C99 source together with the arena layout.
func Emit(p *ir.Plan) (string, Layout, error) {
	e := &emitter{p: p, lay: layoutFor(p)}
	e.prologue()
	for ri := range p.Regions {
		e.region(ri)
	}
	e.entry()
	if e.err != nil {
		return "", Layout{}, e.err
	}
	return e.b.String(), e.lay, nil
}

func (e *emitter) prologue() {
	e.printf(`/* Generated by twill's CPU backend. Do not edit.
 *
 * Every kernel below walks a flat f64 arena. The offsets are constants because
 * the IR's shapes are concrete, so no index is computed from a struct at run
 * time and the C compiler sees the same integers a hand-written kernel would.
 *
 * Two invariants make the output comparable to the interpreter's, bit for bit,
 * and both are load-bearing:
 *
 *   1. No reassociation. Every reduction below accumulates in the same order
 *      internal/tensor does, including parallelSum's fixed 4096-element
 *      blocking, so the answer does not depend on this file being compiled at
 *      all. The build must pass -ffp-contract=off; with contraction on, a
 *      multiply-add would fuse and stop rounding where Go rounds.
 *   2. No fast math. The elementwise operators are the same IEEE operations in
 *      the same order. The transcendentals are libm's rather than Go's, which
 *      is the one place agreement is a tolerance and not an identity.
 */
#include <math.h>
#include <string.h>

#if defined(_WIN32)
#define TWILL_EXPORT __declspec(dllexport)
#else
#define TWILL_EXPORT __attribute__((visibility("default")))
#endif

/* Go's math.Max and math.Min are not C's fmax and fmin: they propagate NaN and
 * they pick a sign for a tie between zeros. Matching them is the difference
 * between a bit-exact backend and one that is nearly right. */
static double twill_max(double x, double y) {
	if (isnan(x) || isnan(y)) return NAN;
	if (x == 0 && y == 0) return signbit(x) ? y : x;
	return x > y ? x : y;
}
static double twill_min(double x, double y) {
	if (isnan(x) || isnan(y)) return NAN;
	if (x == 0 && y == 0) return signbit(x) ? x : y;
	return x < y ? x : y;
}
/* Go's math.Mod is not C's fmod: twill's %% is x - floor(x/y)*y, which follows
 * the sign of the divisor. */
static double twill_mod(double x, double y) { return x - floor(x / y) * y; }

`)
}

// idx renders the C expression for the flat index into a value of shape `from`
// while walking a loop over shape `over`. It is effStrides in internal/tensor,
// unrolled into constants: a broadcast axis contributes nothing, so a broadcast
// costs an addition of zero terms rather than a materialised expansion.
func idx(from, over []int) string {
	if ir.Numel(from) == 1 {
		return "0"
	}
	if shapeEq(from, over) {
		return "o"
	}
	eff := ir.EffStrides(from, over)
	ostr := ir.Strides(over)
	var terms []string
	for d := range over {
		if eff[d] == 0 {
			continue
		}
		var coord string
		switch {
		case ostr[d] == 1 && d == 0:
			coord = "o"
		case ostr[d] == 1:
			coord = fmt.Sprintf("(o %% %d)", over[d])
		case d == 0:
			coord = fmt.Sprintf("(o / %d)", ostr[d])
		default:
			coord = fmt.Sprintf("((o / %d) %% %d)", ostr[d], over[d])
		}
		if eff[d] == 1 {
			terms = append(terms, coord)
		} else {
			terms = append(terms, fmt.Sprintf("%s * %d", coord, eff[d]))
		}
	}
	if len(terms) == 0 {
		return "0"
	}
	return strings.Join(terms, " + ")
}

func shapeEq(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// elemFn emits `static double regN_elem(const double *A, long long o)`, the
// value of `root` at flat index o of the iteration shape, with every absorbed
// producer computed inline. This one function is what a fused region *is*: the
// intermediates are C locals and never touch memory.
func (e *emitter) elemFn(ri int, root ir.Ref, body []ir.Ref, iter []int) {
	g := e.p.Graph
	e.printf("static double reg%d_elem(const double *A, long long o) {\n", ri)
	name := map[ir.Ref]string{}
	for k, r := range body {
		if r == root && g.Nodes[r].Op.Class() != ir.ClassElementwise {
			continue // the root of a reduce region is the reduction itself
		}
		name[r] = fmt.Sprintf("v%d", k)
	}
	// read renders an operand: a body-local register, or a load from the arena.
	read := func(r ir.Ref) string {
		if s, ok := name[r]; ok {
			return s
		}
		off := e.lay.Offset[r]
		if off < 0 {
			e.fail("region %d reads %%%d, which no region materialises", ri, r)
			return "0"
		}
		return fmt.Sprintf("A[%d + %s]", off, idx(g.Nodes[r].Shape, iter))
	}
	for _, r := range body {
		v, ok := name[r]
		if !ok {
			continue
		}
		n := &g.Nodes[r]
		e.printf("\tdouble %s = %s;\n", v, e.expr(n, read))
	}
	if s, ok := name[root]; ok {
		e.printf("\treturn %s;\n}\n\n", s)
	} else {
		// A reduce region whose body is only the root: the value being reduced
		// is a plain load.
		e.printf("\treturn %s;\n}\n\n", read(g.Nodes[root].In[0]))
	}
}

// expr renders one elementwise node as a C expression over its operands.
func (e *emitter) expr(n *ir.Node, read func(ir.Ref) string) string {
	a := func(k int) string { return read(n.In[k]) }
	switch n.Op {
	case ir.OpAdd:
		return fmt.Sprintf("(%s) + (%s)", a(0), a(1))
	case ir.OpSub:
		return fmt.Sprintf("(%s) - (%s)", a(0), a(1))
	case ir.OpMul:
		return fmt.Sprintf("(%s) * (%s)", a(0), a(1))
	case ir.OpDiv:
		return fmt.Sprintf("(%s) / (%s)", a(0), a(1))
	case ir.OpMod:
		return fmt.Sprintf("twill_mod(%s, %s)", a(0), a(1))
	case ir.OpMaximum:
		return fmt.Sprintf("twill_max(%s, %s)", a(0), a(1))
	case ir.OpMinimum:
		return fmt.Sprintf("twill_min(%s, %s)", a(0), a(1))
	case ir.OpLt:
		return fmt.Sprintf("((%s) < (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpLe:
		return fmt.Sprintf("((%s) <= (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpGt:
		return fmt.Sprintf("((%s) > (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpGe:
		return fmt.Sprintf("((%s) >= (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpEq:
		return fmt.Sprintf("((%s) == (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpNe:
		return fmt.Sprintf("((%s) != (%s) ? 1.0 : 0.0)", a(0), a(1))
	case ir.OpNeg:
		return fmt.Sprintf("-(%s)", a(0))
	case ir.OpExp:
		return fmt.Sprintf("exp(%s)", a(0))
	case ir.OpLog:
		return fmt.Sprintf("log(%s)", a(0))
	case ir.OpSqrt:
		return fmt.Sprintf("sqrt(%s)", a(0))
	case ir.OpSin:
		return fmt.Sprintf("sin(%s)", a(0))
	case ir.OpCos:
		return fmt.Sprintf("cos(%s)", a(0))
	case ir.OpTanh:
		return fmt.Sprintf("tanh(%s)", a(0))
	case ir.OpSigmoid:
		return fmt.Sprintf("(1.0 / (1.0 + exp(-(%s))))", a(0))
	case ir.OpRelu:
		return fmt.Sprintf("((%s) > 0 ? (%s) : 0.0)", a(0), a(0))
	case ir.OpSquare:
		return fmt.Sprintf("(%s) * (%s)", a(0), a(0))
	case ir.OpPowScalar:
		return fmt.Sprintf("pow(%s, %s)", a(0), cnum(n.Attr.F))
	case ir.OpClip:
		return fmt.Sprintf("twill_min(twill_max(%s, %s), %s)", a(0), cnum(n.Attr.F), cnum(n.Attr.G))
	case ir.OpWhere:
		return fmt.Sprintf("((%s) != 0 ? (%s) : (%s))", a(0), a(1), a(2))
	}
	e.fail("no C expression for %s", n.Op)
	return "0"
}

// cnum prints a float64 so the C compiler reads back the identical bits.
// %b would be shortest but is not C; the hex float literal is exact and C99.
func cnum(x float64) string {
	return fmt.Sprintf("%s /*%g*/", hexFloat(x), x)
}

func (e *emitter) region(ri int) {
	r := e.p.Regions[ri]
	g := e.p.Graph
	n := &g.Nodes[r.Root]
	off := e.lay.Offset[r.Root]

	switch r.Kind {
	case ir.RegionBuffer:
		return

	case ir.RegionMap:
		e.elemFn(ri, r.Root, r.Body, r.Iter)
		e.printf("static void reg%d(double *A) {\n", ri)
		e.printf("\tfor (long long o = 0; o < %d; o++) A[%d + o] = reg%d_elem(A, o);\n}\n\n",
			ir.Numel(r.Iter), off, ri)

	case ir.RegionReduce:
		e.elemFn(ri, r.Root, r.Body, r.Iter)
		e.reduce(ri, n, off, r.Iter)

	case ir.RegionStructural:
		e.structural(ri, n, off)

	case ir.RegionContract:
		e.contract(ri, n, off)
	}
}

// reduce emits a reduction, preserving internal/tensor's accumulation order
// exactly. docs/DECISIONS.md entry 6 makes determinism a property of the
// language rather than of the machine, and that constraint carries into the
// compiler unchanged: the emitted sum blocks by a fixed 4096, not by anything
// the hardware suggests.
func (e *emitter) reduce(ri int, n *ir.Node, off int, iter []int) {
	N := ir.Numel(iter)
	e.printf("static void reg%d(double *A) {\n", ri)
	switch n.Op {
	case ir.OpSum, ir.OpMean:
		scale := "1.0"
		if n.Op == ir.OpMean {
			scale = cnum(1.0 / float64(N))
		}
		if N < 8192 {
			// tensor.parallelSum runs a plain serial sum below minParallel.
			e.printf("\tdouble s = 0.0;\n")
			e.printf("\tfor (long long o = 0; o < %d; o++) s += reg%d_elem(A, o);\n", N, ri)
		} else {
			// At or above minParallel it sums fixed 4096-element blocks and then
			// adds the partials in block order. Summing each block into a local
			// and adding it to the running total gives the identical sequence of
			// additions without the partials array.
			e.printf("\tdouble s = 0.0;\n")
			e.printf("\tfor (long long blk = 0; blk < %d; blk++) {\n", (N+4095)/4096)
			e.printf("\t\tlong long start = blk * 4096, end = start + 4096;\n")
			e.printf("\t\tif (end > %d) end = %d;\n", N, N)
			e.printf("\t\tdouble p = 0.0;\n")
			e.printf("\t\tfor (long long o = start; o < end; o++) p += reg%d_elem(A, o);\n", ri)
			e.printf("\t\ts += p;\n\t}\n")
		}
		e.printf("\tA[%d] = s * %s;\n}\n\n", off, scale)

	case ir.OpSumAxis, ir.OpMeanAxis:
		before, L, after := axisSpans(iter, n.Attr.Axis)
		scale := "1.0"
		if n.Op == ir.OpMeanAxis {
			scale = cnum(1.0 / float64(L))
		}
		e.printf("\tfor (long long i = 0; i < %d; i++)\n", before)
		e.printf("\tfor (long long j = 0; j < %d; j++) {\n", after)
		e.printf("\t\tdouble s = 0.0;\n")
		e.printf("\t\tlong long base = i * %d + j;\n", L*after)
		e.printf("\t\tfor (long long k = 0; k < %d; k++) s += reg%d_elem(A, base + k * %d);\n", L, ri, after)
		e.printf("\t\tA[%d + i * %d + j] = s * %s;\n\t}\n}\n\n", off, after, scale)

	case ir.OpSumTo:
		N := ir.Numel(iter)
		e.printf("\tmemset(A + %d, 0, %d * sizeof(double));\n", off, ir.Numel(n.Shape))
		e.printf("\tfor (long long o = 0; o < %d; o++) A[%d + %s] += reg%d_elem(A, o);\n}\n\n",
			N, off, idx(n.Attr.Shape, iter), ri)

	default:
		e.fail("no reduction kernel for %s", n.Op)
		e.printf("}\n\n")
	}
}

func axisSpans(shape []int, axis int) (before, length, after int) {
	before, length, after = 1, shape[axis], 1
	for i := 0; i < axis; i++ {
		before *= shape[i]
	}
	for i := axis + 1; i < len(shape); i++ {
		after *= shape[i]
	}
	return
}

func (e *emitter) structural(ri int, n *ir.Node, off int) {
	g := e.p.Graph
	src := n.In[0]
	sOff := e.lay.Offset[src]
	if sOff < 0 {
		e.fail("region %d reads %%%d, which no region materialises", ri, src)
		return
	}
	e.printf("static void reg%d(double *A) {\n", ri)
	switch n.Op {
	case ir.OpReshape:
		e.printf("\tmemmove(A + %d, A + %d, %d * sizeof(double));\n}\n\n", off, sOff, ir.Numel(n.Shape))
	case ir.OpBroadcastTo:
		e.printf("\tfor (long long o = 0; o < %d; o++) A[%d + o] = A[%d + %s];\n}\n\n",
			ir.Numel(n.Shape), off, sOff, idx(g.Nodes[src].Shape, n.Shape))
	case ir.OpTranspose:
		// out[o] = in[sum over d of coord_out[d] * inStride[perm[d]]].
		inShape := g.Nodes[src].Shape
		inStr := ir.Strides(inShape)
		ostr := ir.Strides(n.Shape)
		var terms []string
		for d := range n.Shape {
			st := inStr[n.Attr.Shape[d]]
			if st == 0 || n.Shape[d] == 1 {
				continue
			}
			var coord string
			switch {
			case ostr[d] == 1:
				coord = fmt.Sprintf("(o %% %d)", n.Shape[d])
			default:
				coord = fmt.Sprintf("((o / %d) %% %d)", ostr[d], n.Shape[d])
			}
			terms = append(terms, fmt.Sprintf("%s * %d", coord, st))
		}
		expr := "0"
		if len(terms) > 0 {
			expr = strings.Join(terms, " + ")
		}
		e.printf("\tfor (long long o = 0; o < %d; o++) A[%d + o] = A[%d + %s];\n}\n\n",
			ir.Numel(n.Shape), off, sOff, expr)
	default:
		e.fail("no structural kernel for %s", n.Op)
		e.printf("}\n\n")
	}
}

// contract emits matmul. The loop order and the zero skip are copied from mm()
// in internal/tensor rather than chosen: the order fixes the accumulation
// sequence, and skipping a zero multiplicand is what mm does, so doing anything
// else would change the answer on an operand containing an infinity.
func (e *emitter) contract(ri int, n *ir.Node, off int) {
	g := e.p.Graph
	as, bs := g.Nodes[n.In[0]].Shape, g.Nodes[n.In[1]].Shape
	a2, b2 := as, bs
	if len(as) == 1 {
		a2 = []int{1, as[0]}
	}
	if len(bs) == 1 {
		b2 = []int{bs[0], 1}
	}
	m, k, nn := a2[0], a2[1], b2[1]
	aOff, bOff := e.lay.Offset[n.In[0]], e.lay.Offset[n.In[1]]
	if aOff < 0 || bOff < 0 {
		e.fail("region %d reads an unmaterialised matmul operand", ri)
		return
	}
	e.printf("static void reg%d(double *A) {\n", ri)
	e.printf("\tdouble *C = A + %d; const double *X = A + %d; const double *Y = A + %d;\n", off, aOff, bOff)
	e.printf("\tmemset(C, 0, %d * sizeof(double));\n", m*nn)
	e.printf("\tfor (long long i = 0; i < %d; i++)\n", m)
	e.printf("\tfor (long long p = 0; p < %d; p++) {\n", k)
	e.printf("\t\tdouble aip = X[i * %d + p];\n\t\tif (aip == 0) continue;\n", k)
	e.printf("\t\tfor (long long j = 0; j < %d; j++) C[i * %d + j] += aip * Y[p * %d + j];\n\t}\n}\n\n",
		nn, nn, nn)
}

func (e *emitter) entry() {
	e.printf("TWILL_EXPORT void twill_run(double *A) {\n")
	for ri, r := range e.p.Regions {
		if r.Kind == ir.RegionBuffer {
			continue
		}
		e.printf("\treg%d(A);\n", ri)
	}
	e.printf("}\n")
}
