package main

// A grammar-directed generator for .ra programs.
//
// It is deliberately narrow. Programs are built from a scalar pool and a pool
// of length-3 vectors, so almost everything it emits passes the shape checker
// and reaches the interpreter, which is where a value-representation bug lives.
// A generator that mostly produced shape errors would be diffing the checker's
// error strings over and over and finding nothing.
//
// Loops are bounded by construction, because the harness has to finish.

import (
	"fmt"
	"math/rand"
	"strings"
)

var (
	genUnary  = []string{"exp", "log", "sin", "cos", "sqrt", "tanh", "sigmoid", "relu", "abs"}
	genReduce = []string{"sum", "mean", "max", "min", "prod"}
	genBinop  = []string{"+", "-", "*", "/"}
)

// generate returns a program for a seed. The same seed always gives the same
// program, so a divergence found on a fuzz run is quotable in a bug report and
// can be added to the corpus unchanged.
func generate(seed int64) string {
	g := &gen{r: rand.New(rand.NewSource(seed))}
	g.emit("# generated by tools/diff/run, seed " + fmt.Sprint(seed))
	g.line("let v0 = [%s, %s, %s]", g.lit(), g.lit(), g.lit())
	g.vectors = append(g.vectors, "v0")
	g.line("let s0 = %s", g.lit())
	g.scalars = append(g.scalars, "s0")

	for i := 0; i < 4+g.r.Intn(6); i++ {
		g.statement(i)
	}
	return g.b.String()
}

type gen struct {
	r       *rand.Rand
	b       strings.Builder
	scalars []string
	vectors []string
}

func (g *gen) emit(s string)                    { g.b.WriteString(s + "\n") }
func (g *gen) line(format string, args ...any)  { g.emit(fmt.Sprintf(format, args...)) }
func (g *gen) pick(xs []string) string          { return xs[g.r.Intn(len(xs))] }
func (g *gen) name(prefix string, i int) string { return fmt.Sprintf("%s%d", prefix, i+1) }
func (g *gen) maybe(p int) bool                 { return g.r.Intn(100) < p }
func (g *gen) lit() string                      { return genLiterals[g.r.Intn(len(genLiterals))] }
func (g *gen) scalar() string                   { return g.pick(g.scalars) }
func (g *gen) vector() string                   { return g.pick(g.vectors) }
func (g *gen) declScalar(name, expr string) {
	g.line("let %s = %s", name, expr)
	g.scalars = append(g.scalars, name)
}
func (g *gen) declVector(name, expr string) {
	g.line("let %s = %s", name, expr)
	g.vectors = append(g.vectors, name)
}

// genLiterals stays small and includes the awkward ones on purpose: a value
// whose decimal rendering rounds, a negative, and a zero that makes log and
// division interesting.
var genLiterals = []string{"0.1", "0.2", "1.0", "2.0", "-1.5", "3.25", "0.0", "1e-8", "7.0"}

func (g *gen) statement(i int) {
	switch g.r.Intn(8) {
	case 0:
		g.declScalar(g.name("s", i+1), fmt.Sprintf("%s %s %s", g.scalar(), g.pick(genBinop), g.scalar()))
	case 1:
		g.declScalar(g.name("s", i+1), fmt.Sprintf("%s(%s)", g.pick(genUnary), g.scalar()))
	case 2:
		g.declScalar(g.name("s", i+1), fmt.Sprintf("%s(%s)", g.pick(genReduce), g.vector()))
	case 3:
		g.declVector(g.name("v", i+1), fmt.Sprintf("%s %s %s", g.vector(), g.pick(genBinop), g.vector()))
	case 4:
		g.declVector(g.name("v", i+1), fmt.Sprintf("%s(%s) * %s", g.pick(genUnary), g.vector(), g.scalar()))
	case 5:
		g.declScalar(g.name("s", i+1), fmt.Sprintf("%s @ %s", g.vector(), g.vector()))
	case 6:
		// A bounded accumulation loop, which is the shape of every hot path the
		// value representation touches.
		acc := g.name("s", i+1)
		g.line("let %s = %s", acc, g.lit())
		g.line("for k in range(%d) {", 1+g.r.Intn(5))
		g.line("  %s = %s %s %s", acc, acc, g.pick(genBinop), g.scalar())
		g.emit("}")
		g.scalars = append(g.scalars, acc)
	case 7:
		// Differentiating is the whole point of the language, so a fixed share
		// of programs must reach the tape rather than the scalar fast path.
		fn := g.name("f", i+1)
		body := fmt.Sprintf("%s(x) * %s + x * x", g.pick(genUnary), g.scalar())
		g.line("fn %s(x) = %s", fn, body)
		g.declScalar(g.name("d", i+1), fmt.Sprintf("grad(%s)(%s)", fn, g.scalar()))
		if g.maybe(40) {
			g.declVector(g.name("gv", i+1), fmt.Sprintf("grad(fn(x) = sum(%s(x)))(%s)", g.pick(genUnary), g.vector()))
		}
	}
}
